### ISSUE TITLE
你好我用了下您的项目，ios平移闪烁的问题有遇到过吗

### ISSUE THREAD

**Issue by z970445720** [hellodigua/vue-danmaku#9]
ios浏览器中弹幕滚动会闪烁

**Comment by hellodigua** [comment]
您好，由于手头暂时没有iOS设备，能帮忙测试一下吗：
1. 请问 https://hellodigua.github.io/vue-danmaku/ 这个Demo在出现问题的浏览器上一样会闪烁吗？
2. 在config参数中将 debounce 和 speed 参数配置的高一点，还会出现这样的情况吗？（如果还是会出现，请附上您的iOS版本和设备型号，我去找台机器优化一下）

**Comment by hellodigua** [comment]
您好，由于手头暂时没有iOS设备，能帮忙测试一下吗：
1. 请问 https://hellodigua.github.io/vue-danmaku/ 这个Demo在出现问题的浏览器上一样会闪烁吗？
2. 在config参数中将 debounce 和 speed 参数配置的高一点，还会出现这样的情况吗？（如果还是会出现，请附上您的iOS版本和设备型号，我去找台机器优化一下）

**Comment by z970445720** [comment]
> 您好，由于手头暂时没有iOS设备，能帮忙测试一下吗：
> 
> 1. 请问https://hellodigua.github.io/vue-danmaku/这个Demo在出现问题的浏览器上一样会闪烁吗？
> 2. 在配置参数中将debounce和速度参数配置的高一点，将会出现这样的情况吗？（如果还是会出现，请附上您的iOS版本和设备型号，我去找台机器优化一下）

已经解决此问题，宽度设置百分之百会出现此问题，需将.danmus类 宽度设置成99%或其他值即可。 iPhone6机型

**Comment by yliaz** [comment]
我也遇到了这个问题，排查出的原因是 @keyframe 中只写了from没写to，在safari浏览器中会造成闪烁问题
```css
@keyframes moveLeft {
        from {
          transform: translate3d(100%, 0, 0);
        }
        to {
          transform: translate3d(var(--barrage-left-offset), 0, 0);
        }
      }
```
